community/urls.py
from django.urls import path
from . import views

app_name = 'community'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/<int:movie_id>/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comments_update, name='comments_update'),
    path('<int:article_pk>/like/', views.like, name='like'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name="index"),
    path('preference/', views.preference, name='preference'),
    path('released_thisyear/', views.released_thisyear, name="released_thisyear"),
    path('alone/', views.alone, name="alone"),
    path('couple/', views.couple, name="couple"),
    path('together/', views.together, name="together"),
    path('<title>/<int:date>/', views.naver_link, name='naver_link'),
    path('<int:movie_id>/', views.detail, name='detail'),
    path('search/', views.search, name='search'),
    path('search_title/<str:searchword>', views.search_title, name='search_title'),
]

movies/models.py
from django.db import models


# Create your models here.
# from django.contrib.auth import get
class Genre(models.Model):
    genre_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


# class Actor(models.Model):
#     name = models.CharField(max_length=20)

#     def __str__(self):
#         return self.name


# class Country(models.Model):
#     iso = models.CharField(max_length=10, primary_key=True)
#     name = models.CharField(max_length=20)

#     def __str__(self):
#         return  self.name


class Movie(models.Model):
    movie_id = models.IntegerField(primary_key=True)
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    poster_path = models.CharField(max_length=200, null=True)
    backdrop_path = models.CharField(max_length=200, null=True)
    original_language = models.CharField(max_length=10)
    original_title = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    vote_average = models.FloatField()
    overview = models.TextField(null=True)
    release_date = models.DateField(auto_now=False)
    genres = models.ManyToManyField(Genre, related_name='movies')
    # runtime = models.IntegerField(null=True)
    # country = models.ManyToManyField(Country, related_name='movies')
    # actors = models.ManyToManyField(Actor)

    def __str__(self):
        return self.title

movies/views.py
import random
import requests
import os
from datetime import datetime

from .models import Movie, Genre
from .serializers import MovieSerializer

from django.shortcuts import render, redirect

from bs4 import BeautifulSoup
from django.views.decorators.http import require_http_methods, require_GET, require_POST
# from django.http import JsonResponse

from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from rest_framework.decorators import permission_classes
from rest_framework.permissions import IsAuthenticated



# Create your views here.
def index(request):
    return render(request, 'movies/index.html')
    
# 0. 유저의 선호도를 분석해서 최적의 영화를 추천하는 알고리즘
# 1. 유저의 선호도 정보를 받는다.(문자열 형태 ex) 3333333333333333333)
# 2. 선호도 정보와 장르id 매칭
# => 선호도 우선순위(한국인이 좋아하는 영화장르 통계조사 참고)
# 통계: 액션, 드라마, 스릴러, 로코, SF, 판타지, 코미디, 느와르, 미스터리, 다큐, 공포, 멜로, 뮤지컬
# DB: 액션(28), 드라마(18), 스릴러(53), 로맨스(10749), 가족(10751), SF(878), 판타지(14),
#     모험(12), 코미디(35), 범죄(80), 미스터리(9648), 애니메이션(16), 다큐멘터리(99), 
#     역사(36), 전쟁(10752), 공포(27), 음악(10402), 서부(37), TV영화(10770) 
# 3. DB순서대로 각 index의 숫자가 사용자의 선호도 (3621763... 인 사용자는 액션:3, 드라마:6...)
# 4. for문을 활용해 선호도가 높은 순서대로 숫자를 하나씩 뽑아낸뒤 해당 장르의 코드를 뽑아낸다.
# 5. 연관성 최우선 으로 추출
# 6. 기타 영화는 선호장르에서 랜덤으로 뽑아서 제공


def recommend_preference_algorithm(code):
    match = [28, 18, 53, 10749, 10751,
                878, 14, 12, 35, 80,
                9648, 16, 99, 36, 10752, 
                27, 10402, 37, 10770
            ]

    pref_list = []

    # 선호도 코드에서 장르 뽑아내는 알고리즘(선호장르 5개)
    # 5개를 뽑는 이유는 평균적으로 영화가 2개정도의 장로가 혼합
    # 10개 정도의 장르적 특징을 가지는 영화를 제공 (5 Combination 2)
    for cnt in range(9, 0, -1):
        for prefer in range(len(code)):
            if int(code[prefer]) == cnt:
                pref_list.append(match[prefer])
            if len(pref_list) > 4:
                break
        if len(pref_list) > 4:
            break

    prefer_movie = [[] for _ in range(5)]  
    # 관심도가 유사한 장르를 뽑아서 보여주기
    movie_list = Movie.objects.all()
    for movie in movie_list:
        num = 0
        for gen in movie.genres.all():
            if gen.genre_id in pref_list:
                num += 1
        if num > 0:
            prefer_movie[num-1].append(movie)

    show_movie = []
    # 뽑아낸 선호장르 영화리스트에서 12개 뽑아내기
    for num in range(4, -1, -1):
        length = len(prefer_movie[num])
        if length > 0 and len(show_movie) + length <= 12:
            for mo in prefer_movie[num]:
                show_movie.append(mo)
        elif length > 0:
            # 12개를 초과한다면 12개를 맞추도록 랜덤으로 추출
            randomlist = random.sample(prefer_movie[num], 12 - len(show_movie))
            for rand in randomlist:
                show_movie.append(rand)

    return show_movie


def preference(request):
    # 승인된 유저라면 해당유저의 정보를 바탕으로 추천
    if request.user.is_authenticated:
        pref_code = request.user.preference_code
        recommend_movie_list = recommend_preference_algorithm(pref_code)
        
    # 승인되지 않은 유저라면 로그인 요청하기
    else:
        return redirect('accounts:login')

    comment = '취향에 맞춰 추천해요!'
    context = {
        'recommend_movie_list': recommend_movie_list,
        'comment': comment,
    }
    return render(request, 'movies/recommendation.html', context)


def naver_link(request, title, date):
    
    BASE_URL = "http://search.naver.com/search.naver?query="
    url = BASE_URL + title + '%20' + str(date)
    print('###############')
    print(url)
    
    req = requests.get(url)
    html = req.text
    soup = BeautifulSoup(html, "html.parser")
    try:
        search_link = soup.find("div", class_="title_area")
        detail_link = search_link.find("a")["href"]

        return redirect(detail_link)

    except AttributeError as e:
        url = BASE_URL + title
        req = requests.get(url)
        html = req.text
        soup = BeautifulSoup(html, "html.parser")
        try:
            search_link = soup.find("div", class_="title_area")
            detail_link = search_link.find("a")["href"]
            print(e)
            return redirect(detail_link)
        
        except (TypeError, AttributeError):
            url = BASE_URL + '영화 ' + title
            print(url)
            req = requests.get(url)
            html = req.text
            soup = BeautifulSoup(html, "html.parser")
            try:
                search_link = soup.find("div", class_="title_area")
                detail_link = search_link.find("a")["href"]
                return redirect(detail_link)

            # 다음링크
            except AttributeError:
                DAUM_URL = "http://search.daum.net/search?q="
                url = DAUM_URL + title + str(date)
                req = requests.get(url)
                html = req.text
                soup = BeautifulSoup(html, "html.parser")
                try:
                    search_link = soup.find("div", class_="link_tit")
                    detail_link = search_link.find("a")["href"]
                    print(detail_link)
                    return redirect(detail_link)

                except AttributeError:
                    detail_link = BASE_URL + title
                    return redirect(detail_link)
                
    return redirect(detail_link)


def return_link(title, date):
    
    BASE_URL = "http://search.naver.com/search.naver?query="
    url = BASE_URL + title + '%20' + str(date)
    print('###############')
    print(url)
    
    req = requests.get(url)
    html = req.text
    soup = BeautifulSoup(html, "html.parser")
    try:
        search_link = soup.find("div", class_="title_area")
        try:
            detail_link = search_link.find("a")["href"]
            req2 = requests.get(detail_link)
            html2 = req2.text
            soup2 = BeautifulSoup(html2, "html.parser")
            overview = soup2.find("p", class_="con_tx")
            return overview
        except:
            overview = ''
            return overview


    except AttributeError as e:
        url = BASE_URL + title
        req = requests.get(url)
        html = req.text
        soup = BeautifulSoup(html, "html.parser")
        try:
            search_link = soup.find("div", class_="title_area")
            detail_link = search_link.find("a")["href"]
            req2 = requests.get(detail_link)
            html2 = req2.text
            soup2 = BeautifulSoup(html2, "html.parser")
            overview = soup2.find("p", class_="con_tx")

            return overview
        
        except (TypeError, AttributeError):
            url = BASE_URL + '영화 ' + title
            print(url)
            req = requests.get(url)
            html = req.text
            soup = BeautifulSoup(html, "html.parser")
            try:
                search_link = soup.find("div", class_="title_area")
                detail_link = search_link.find("a")["href"]
                req2 = requests.get(detail_link)
                html2 = req2.text
                soup2 = BeautifulSoup(html2, "html.parser")
                overview = soup2.find("p", class_="con_tx")

                return overview

            # 다음링크
            except AttributeError:
                DAUM_URL = "http://search.daum.net/search?q="
                url = DAUM_URL + title + str(date)
                req = requests.get(url)
                html = req.text
                soup = BeautifulSoup(html, "html.parser")
                try:
                    search_link = soup.find("div", class_="link_tit")
                    detail_link = search_link.find("a")["href"]
                    print(detail_link)
                    return detail_link

                except AttributeError:
                    detail_link = BASE_URL + title
                    return detail_link
                
    return detail_link


def detail(request, movie_id):
    # 0. reco.html페이지에서 버튼을 클릭시 movie.movie_id를 url에 담아서 보내기
    # 1. movie 인스턴스 생성
    # 2. movie.article.all() ? 로 전부 불러와서 article_list형태로 넘겨주기
    movie = Movie.objects.get(movie_id=movie_id)
    if len(movie.overview):
        link = ''
    else:
        link = return_link(movie.title, movie.release_date.year)
    # API 요청
    import requests
    BASE_URL = 'https://www.googleapis.com/youtube/v3/search?'
    API_KEY = os.environ.get('API_KEY')
    REQUEST_URL = BASE_URL + 'part=snippet' + f'&key={API_KEY}' + f'&q=movie%20{movie.original_title}%20trailer'  
    response = requests.get(REQUEST_URL)
    response = response.json()
    videoID = response["items"][0]["id"]["videoId"]
    print(videoID)
    

    VIDEO_URL = 'www.youtube.com/embed/' + videoID
    print(VIDEO_URL)

    articles = movie.article_set.all()
    context = {
        'movie': movie,
        'articles': articles,
        'link': link,
        'VIDEO_URL': VIDEO_URL,
    }
    return render(request, 'movies/movie_detail.html', context)


def search(request):
    keyword = str(request.GET.get('search'))
    # 1. 키워드 - 제목 필터링(title-str)
    title_related = Movie.objects.filter(title__contains=keyword)
    # 2. 키워드 - 줄거리 필터링(overview-str)
    overview_related = Movie.objects.filter(overview__contains=keyword)
    # 3. 키워드 - 개봉일 필터링(release_date.-str로 변환해서 사용?)
    date_related = Movie.objects.filter(release_date__contains=keyword)

    context = {
        'title_related': title_related,
        'overview_related': overview_related,
        'date_related': date_related,
    }
    return render(request, 'movies/search.html', context)


@api_view(['GET'])
def search_title(request, searchword):
    movies = Movie.objects.filter(title__contains=searchword)
    serializer = MovieSerializer(movies, many=True)

    return Response(data=serializer.data)


# 규칙 1. comment로 멘트 넘겨주기(어떤 알고리즘인지 표시)
# 규칙 2. 영화목록은 recommend_movie_list 로 넘겨주기
def released_thisyear(request):
    # 현재년도 가져오기
    this_year = datetime.now().year
    movies = Movie.objects.filter(release_date__contains=this_year)
    movie_list = []
    random_list = []
    # 3개씩 끊어서 보여주기(1~2개 단위로 끊기지 않게)

movies/templates/movies/_movie_trailer.html
<!-- Modal -->
<div class="modal fade" id="trailerModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog d-flex justify-content-center" role="document">
    <div class="modal-content" style="background-color: rgba(17, 5, 2, 0.8); width: 52rem;">
      <div class="modal-header">
        <h5 class="text-center modal-title base-title-font" id="exampleModalLabel" style="color: white;">{{ movie.title }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: #ffffff;">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body d-flex justify-content-center align-items-center">
        <iframe 
          src="//{{ VIDEO_URL }}"
          frameborder="0" 
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
          allowfullscreen
          style="height: 30rem; width: 48rem;"
        >
        </iframe>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-color-lightcrimson base-title-font" data-dismiss="modal">Close</button>
        <a href="//www.youtube.com/results?search_query={{ movie.title }}">
          <button type="button" class="btn btn-color-lightcrimson base-title-font">다른 영상 보기
          </button>
        </a>
      </div>
    </div>
  </div>
</div>

movies/templates/movies/movie_detail.html
{% extends 'base.html' %}

{% block title %}
  MoviePop | {{ movie.title }}
{% endblock title %}

<head>
  {% block extrahead %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'movies/css/movie_detail.css' %}">
  {% endblock extrahead %}
</head>

{% block content %}

<div class="container base-font bg-img p-0" data-backgroundimg="https://image.tmdb.org/t/p/w500{{ movie.backdrop_path }}">
  <div class="media" style="background: rgba(0, 0, 0, 0.7);">
    <img 
      src="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" 
      class="align-self-start mr-3 mb-3" 
      alt="No Movie image"
      style="width: 300px; height: 485px;"
    >
    <div class="media-body ml-2 mr-2">
      <h2 class="mt-2" style="font-weight: bold;">{{ movie.title }}</h2>
      <h5 class="mt-1" style="opacity: 0.5;">{{ movie.original_title }} | {{ movie.release_date.year }}</h5>
      <hr class="accounts-hr-color">

      <div class="my-2 base-btn-font">
        <h5 style="display: inline-block;">평점: </h5>
        <h5 id="vote-data" style="display: None;">{{ movie.vote_average }}</h5>
        <h5 style="display: inline-block;">
        <span id="star-2" class="fa fa-star base-color"></span>
        <span id="star-4" class="fa fa-star base-color"></span>
        <span id="star-6" class="fa fa-star base-color"></span>
        <span id="star-8" class="fa fa-star base-color"></span>
        <span id="star-10" class="fa fa-star base-color"></span>
        ({{ movie.vote_count }})</h5>
      </div>
      {% if movie.overview|length > 0 %}
        <p class="base-font">{{ movie.overview }}</p>
      {% else %}
        <a class="base-font review-write-go" href="{{ link }}">{{ link }}</a>
      {% endif %}
      {% comment %} 평점은 별모양으로 표기예정 {% endcomment %}
      <hr>
      {% comment %} 리뷰 버튼 {% endcomment %}
      <hr>
      <hr>
    </div>
  </div>
  <hr class="accounts-hr-color m-0 p-0">
{% comment %} 리뷰 리스트{% endcomment %}
  <div style="background-color: rgba(0, 0, 0, 0.7);">
  <br>
  <div class="d-flex justify-content-between align-items-center">
    <h2 class="ml-5 mb-0 base-brightcrimson base-title-font" style="display: inline-block;">리뷰</h2>
    <div class="d-flex content-align-right">
      {% include 'movies/_movie_trailer.html' %}

      <a class="btn back-btn btn-color-lightcrimson ml-auto btn-font mr-4" style="color: rgba(17, 5, 2, 1);" data-toggle="modal" data-target="#trailerModal">
        예고편 보기
      </a>
      <a class="btn back-btn btn-color-lightcrimson ml-auto btn-font mr-4" style="color: rgba(17, 5, 2, 1);" href="{% url 'community:create' movie.movie_id %}">
        리뷰쓰기
      </a>
    </div>
  </div>

  <hr>
    {% if articles|length %}
      {% for article in articles %}
        <ul class="mb-0">
        {% comment %} <hr class="accounts-hr-color mr-5 mt-0"> {% endcomment %}
        <a 
          class="btn mb-0 review-read-go base-title-font" 
          style="font-size: 18px;" 
          href="{% url 'community:detail' article.pk %}"
        >
          ⭐{{ article.score }} | {{ article.title }} | {{ article.user.nickname }}
        </a>
        <br>
        <br>
        </ul>
      {% endfor %}
    {% else %}
      <a 
        class="btn ml-4 review-write-go"
        href="{% url 'community:create' movie.movie_id %}"
      >
        첫 리뷰를 남겨주세요!
      </a>
    {% endif %}
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>

<script rel="stylesheet" src="{% static 'movies/js/movie_detail.js' %}"></script>

{% endblock content %}

movies/templates/movies/recommendation.html
{% extends 'base.html' %}

{% block title %}
  MoviePop | 추천영화
{% endblock title %}

<head>
  {% block extrahead %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'movies/css/recommendation.css' %}">
  {% endblock extrahead %}
</head>

{% block content %}
<br>
<h3 class="base-font">{{ comment }}</h3>
<br>
<div class='d-flex row base-font' style="width: 980px">
  {% for movie in recommend_movie_list %}
    <div class="card bg-dark text-white div-size m-2 movie-card">
      <img 
        src="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" 
        class="card-img hover-img img-size" 
        alt="..."
      >
      <div 
        class="card-img-overlay hover-img bg-color"
        style="position: absolute; top: 22rem;"
      >
        {% comment %} <div style="height: 22rem;">
        </div> {% endcomment %}
        <div>
          <div class="h4 card-title text-truncate locate base-title-font text-center">{{ movie.title }}</div>
          {% if movie.overview|length > 0 %}
            <p class="card-text text-truncate base-font">{{ movie.overview }}</p>
          {% else %}
            <p class="card-text text-truncate base-font">Detail페이지에서 줄거리를 확인해주세요</p>
          {% endif %}
          {% comment %} <p class="card-text">{{ movie.release_date }}</p> {% endcomment %}
          <div class="d-flex justify-content-around">
            <a
              href="{% url 'movies:detail' movie.movie_id %}" 
              class="btn btn-color-ivory bottom-btn"
              style="color: rgba(255, 255, 255, 1); width: 7.5rem;"
            >
              Detail
            </a>
            <a
              href="{% url 'movies:naver_link' movie.title movie.release_date|date:"Y" %}" 
              class="btn btn-color-ivory bottom-btn" 
              style="color: rgba(255, 255, 255, 1); width: 7.5rem;"
            >
              Link
            </a>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

<script rel="stylesheet" src="{% static 'movies/js/recommendation.js' %}"></script>

{% endblock content %}

movies/templates/movies/search.html
{% extends 'base.html' %}

{% block title %}
  MoviePop | 영화검색
{% endblock title %}


{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'movies/css/search.css' %}">
{% endblock extrahead %}


{% block content %}

  <div class="base-font title-color">
    <h3>제목</h3>
    <hr class="accounts-hr-color">
    {% if title_related %}
    <div class="list-group">
      {% for movie in title_related %}
        <div 
          class="list-group-item list-group-item-action p-1 pl-3"
          style="background-color: rgba(17, 5, 2, 1);"
        >
          <img 
            src="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" 
            alt="No poster image"
            style="height: 50px; width: 30px; display: inline-block;"
          >
          <a 
            href="{% url 'movies:detail' movie.movie_id %}"
            class="btn a-color-white"
            style="font-size: 20px; display: inline-block; width: 220px; white-space: nowrap; overflow: hidden;"
          >
          {{ movie.title }}
          </a>
        </div>
      {% endfor %}
    </div>
    {% else %}
      <h5 class="p-1 pl-3">검색결과가 없습니다.</h5>
    {% endif %}

    <hr>
    <h3 class="title-color">줄거리</h3>
    <hr class="accounts-hr-color">
    {% if overview_related|length %}
    <div class="list-group">
    {% for movie in overview_related %}
      <div
        class="list-group-item list-group-item-action p-1 pl-3"
        style="background-color: rgba(17, 5, 2, 1)"
      >
        <img 
          src="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" 
          alt="No poster image"
          style="height: 50px; width: 30px; display: inline-block;"
        >
        <a
          href="{% url 'movies:detail' movie.movie_id %}" 
          class="btn a-color-white p-0"
          style="display: inline-block; width: 220px; white-space: nowrap; overflow: hidden; font-weight: bold;"
        >
        {{ movie.title }}
        </a>
        <a 
          class="btn a-color-white text-truncate"
          href="{% url 'movies:detail' movie.movie_id %}" 
          style="display: inline-block; width: 630px; white-space: nowrap;"
        >
           {{ movie.overview }}
        </a>
      </div>
    {% endfor %}
    </div>
    {% else %}
      <h5 class="p-1 pl-3">검색결과가 없습니다.</h5>
    {% endif %}

    <hr>
    <h3>개봉일</h3>
    <hr class="accounts-hr-color">
    {% if date_related|length %}
    <div class="list-group">
      {% for movie in date_related %}
          <a
            href="{% url 'movies:detail' movie.movie_id %}" 
            class="btn a-color-white"
            style="display: inline-block; width: 200px; white-space: nowrap; font-weight: bold;"
          >
          {{ movie.title }} | {{ movie.release_date }}
          </a>
      {% endfor %}
    </div>
    {% else %}
      <h5 class="p-1 pl-3">검색결과가 없습니다.</h5>
    {% endif %}
    <br>
  </div>
{% endblock content %}