accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
    path('detail/<int:user_pk>', views.detail, name='detail'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/<int:movie_id>/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comments_update, name='comments_update'),
    path('<int:article_pk>/like/', views.like, name='like'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name="index"),
    path('preference/', views.preference, name='preference'),
    path('released_thisyear/', views.released_thisyear, name="released_thisyear"),
    path('alone/', views.alone, name="alone"),
    path('couple/', views.couple, name="couple"),
    path('together/', views.together, name="together"),
    path('<title>/<int:date>/', views.naver_link, name='naver_link'),
    path('<int:movie_id>/', views.detail, name='detail'),
    path('search/', views.search, name='search'),
    path('search_title/<str:searchword>', views.search_title, name='search_title'),
]

community/models.py
from django.db import models
from django.conf import settings
from movies.models import Movie
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, default=True)
    title = models.CharField(max_length=100)
    content = models.TextField()
    score = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    image = models.ImageField(upload_to='images/', blank=True, null=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

community/forms.py
from django import forms
from .models import Article, Comment


class ArticleMovieCreationForm(forms.ModelForm):
    
    class Meta:
        model = Article
        fields = ['title', 'content', 'score', 'image']
        # exclude = ['user',]


class ArticleUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Article
        fields = ['title', 'content', 'score']
        # exclude = ['user',]


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        # fields = '__all__'
        exclude = ['article', 'user', ]

community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST

from django.core.paginator import Paginator

from .models import Article, Comment
from movies.models import Movie
from .forms import CommentForm, ArticleMovieCreationForm, ArticleUpdateForm

from django.http import JsonResponse

from rest_framework.decorators import api_view

match = [28, 18, 53, 10749, 10751,
            878, 14, 12, 35, 80,
            9648, 16, 99, 36, 10752, 
            27, 10402, 37, 10770
        ]


# Create your views here.
def index(request):
    articles = Article.objects.order_by('-pk')
    ARTICLE_FOR_PAGE = 8
    paginator = Paginator(articles, ARTICLE_FOR_PAGE)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    startpostnumber = 1
    endpostnumber = len(articles)
    try:
        if int(page):
            if len(articles):
                startpostnumber = (int(page) - 1) * ARTICLE_FOR_PAGE + 1
                if len(articles) <= int(page) * ARTICLE_FOR_PAGE:
                    endpostnumber = len(articles)
                else:
                    endpostnumber = int(page) * ARTICLE_FOR_PAGE
            else:
                startpostnumber = endpostnumber = 0
        else:
            startpostnumber = endpostnumber = 0
            
    except:
        if len(articles):
            startpostnumber = 1
            if len(articles) <= ARTICLE_FOR_PAGE:
                endpostnumber = len(articles)
            else:
                endpostnumber = ARTICLE_FOR_PAGE
        else:
            startpostnumber = endpostnumber = 0

    context = {
        'articles': articles,
        'posts': posts,
        'startpostnumber': startpostnumber,
        'endpostnumber': endpostnumber,
    }
    return render(request, 'community/index.html', context)


# 점수 계산 함수(장르선호도, 평점)
def cal(genre_pref, sco):
    # 몫을 계산하는 이유는 float은 string으로 전환되지 않기 때문이다.
    genre_pref = (genre_pref + sco) // 2
    return str(genre_pref)


# 평점을 선호코드에 반영하는 알고리즘
def score_pref_algorithm(score, code, genres):
    # index 추출
    genre_idx = []
    for genre in genres:
        genre_idx.append(match.index(int(genre.genre_id)))
    for idx in genre_idx:
        code = code[:idx] + cal(int(code[idx]), score) + code[idx+1:]
    # 영화 한편 시청시 관련없는 장르는 관심도 1씩 감소
    # 이유) 최근 시청한 영화에 가중치를 주기위해서
    for code_seq in range(19):
        if int(code[code_seq]) > 3 and code_seq not in genre_idx:
            code = code[:code_seq] + str(int(code[code_seq])-1) + code[code_seq+1:]
    return code


@login_required
@require_http_methods(['GET', 'POST'])
def create(request, movie_id):
    movie = Movie.objects.get(movie_id=movie_id)
    if request.method == 'POST':
        form = ArticleMovieCreationForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.movie = Movie.objects.get(movie_id=movie_id)
            article.save()
            # 2-1. 유저정보에서 필요한 정보를 추출(평점, 선호코드)
            user_score = article.score
            user_pref_code = request.user.preference_code
            movie_genres = article.movie.genres.all()
            # 2-2. 평점 => 선호도 반영 알고리즘에 넣기
            new_pref_code = score_pref_algorithm(
                user_score,
                user_pref_code,
                movie_genres
            )
            request.user.preference_code = new_pref_code
            request.user.save()
            return redirect('community:detail', article.pk)
    else:
        form = ArticleMovieCreationForm()
        # 1-1. 폼에 입력
    context = {
        'form': form,
        'movie': movie,
    }
    return render(request, 'community/create.html', context)


def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    comment_form = CommentForm()
    comments = article.comment_set.all()
    movie = article.movie
    score_1 = '🌕' * (article.score//2)
    score_2 = '🌑' * (5-(article.score//2))
    if article.score % 2:
        score_half = '🌗'
        score_2 = '🌑' * ((5-(article.score//2))-1)
        score = score_1 + score_half + score_2
    else:
        score = score_1 + score_2
    
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
        'movie': movie,
        'score': score,
    }
    return render(request, 'community/detail.html', context)


# prev_score => new_score 반영함수
def update_cal(genre_pref, prev, new):
    genre_pref *= 2
    # 기존 점수가 높았는데 한동안 해당 장르를 안보다가 평점을 낮게 수정하면 오류발생
    # ex) 9점 부여 => 이후에 관심도 3까지 떨어졌을때 글의 평점을 2점으로 수정
    # (3 - 9 + 2) // 2 => -2 이므로 오류 발생 => 음수일 경우 0으로 변경
    if (genre_pref - prev + new) // 2 < 0:
        new_pref = 0
    else:
        new_pref = (genre_pref - prev + new) // 2
    return str(new_pref)


# 업데이트된 스코어 => 선호코드 반영 함수
def updated_score_pref(prev, new, code, genres):
    # 1. 기존 선호코드 idx 추출
    # 2. idx별 장르 선호도에 2를 곱한뒤 prev_score를 뺀다.
    # 3. new_score를 더한뒤 2로 나눈다.
    # 4. 몫을 반영한다.
    genre_idx = []
    for genre in genres:
        genre_idx.append(match.index(int(genre.genre_id)))
    for idx in genre_idx:
        code = code[:idx] + update_cal(int(code[idx]), prev, new) + code[idx+1:]
    return code


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    # 기존 리뷰 스코어, 장르 담기
    prev_rvw_score = article.score
    movie_genres = article.movie.genres.all()
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleUpdateForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                form.save()
                # 새로운 리뷰 스코어, 사용자 선호코드
                new_rvw_score = article.score
                prev_user_pref = request.user.preference_code
                # 함수실행
                new_user_pref = updated_score_pref(
                    prev_rvw_score,
                    new_rvw_score,
                    prev_user_pref,
                    movie_genres
                )
                # 저장하기
                request.user.preference_code = new_user_pref
                request.user.save()
                return redirect('community:detail', article.pk)
        else:
            form = ArticleUpdateForm(instance=article)
    else:
        return redirect('community:index')
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'community/update.html', context)


@require_POST
def delete(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        if request.user == article.user:
            article.delete()
            return redirect('community:index')
    return redirect('community:detail', article.pk)

def number_length(num):
    if len(str(num)) == 1:
        num = '0' + str(num)
    return num

def transtime(year, month, day, hour, minute):
    # 월별 마지막 일
    monthday = [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    # 윤달인 경우
    if (year % 4 == 0 and year % 100) or year % 400 == 0:
        monthday[2] = 29
    # 영국시간 => 한국시간
    hour += 9
    # 날짜가 달라질 경우
    if hour >= 24:
        day += 1
        hour -= 24
        if monthday[month] < day:
            day -= monthday[month]
            month += 1
            if month > 12:
                year += 1
                month -= 12

    # 기존 형식과 동일한 두자릿 수로 바꿔주기
    month = number_length(month)
    day = number_length(day)
    hour = number_length(hour)
    minute = number_length(minute)
    
    print(year, month, day, hour, minute)
    return f'{year}/{month}/{day} {hour}:{minute}'
        
        


@require_POST
def comments_create(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.article_id = article.pk
            comment.save()
        # year, month, day, hour, minute
        created_at = transtime(comment.created_at.year, comment.created_at.month, comment.created_at.day, comment.created_at.hour, comment.created_at.minute)
        updated_at = transtime(comment.updated_at.year, comment.updated_at.month, comment.updated_at.day, comment.updated_at.hour, comment.updated_at.minute)        
        data = {
            'id': comment.id,
            'article_id': article.id,
            'username': comment.user.username,
            'content': comment.content,
            'count': article.comment_set.all().count(),
            'created_at': created_at,
            'updated_at': updated_at,
        }
        return JsonResponse(data)


@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            data = {
                'id': comment.id,
                'article_id': article.id,
                'username': comment.user.username,
                'content': comment.content,
                'count': article.comment_set.all().count(),
            }
            comment = comment.delete()
            return JsonResponse(data)


@require_POST
def like(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        user = request.user
        print('a')

        if article.like_users.filter(pk=user.pk).exists():
            article.like_users.remove(user)
            liked = False
        else:
            article.like_users.add(user)
            liked = True
        
        like_status = {
            'liked': liked,

community/templates/community/_comment.html
{% if request.user.is_authenticated %}
  <form class="comment-form" action="{% url 'community:comments_create' article.pk %}" method="POST">
    {% csrf_token %}
    <div class="input-group d-flex align-items-center justify-content-between">
      <input type="text" name="content" maxlength="200" required id="id_content" class="form-control" placeholder="댓글을 입력해주세요" aria-describedby="button-addon2">
      <div class="input-group-append">
        <input class="btn icon-to-button-comment" type="submit" value="&#xf14a;" id="button-addon2" style="font-size: 3rem;">
      </div>
    </div>
  </form>
{% else %}
  <a href="{% url 'accounts:login' %}" class="base-font">[댓글을 작성하려면 로그인 하세요.]</a>
{% endif %}

community/templates/community/_commentlist.html
<div id="comment-list-{{ article.pk }}">
{% for comment in article.comment_set.all %}
	<div>
		<div class="d-flex justify-content-between">
			<div>
				<strong class="base-title-font h4">{{ comment.user }}</strong>
				{% if comment.user == user %}
					<!--댓글 삭제-->
					<i class="far fa-trash-alt delete-comment icon-to-button-delete mx-1" id="delete-{{ comment.id }}" data-id="{{ comment.id }}"></i>
					<!--댓글 수정-->
					<i id="update-{{ comment.id }}" class="fas fa-edit update-comment icon-to-button-update ml-1" data-id="{{ comment.id }}"></i>
				{% endif %}
			</div>
			<div class="" style="font-size: 0.8rem;">
				<div>
					댓글 생성 {{ comment.created_at|date:"Y/m/d H:i" }}
				</div>
				<div>
					최근 수정 {{ comment.updated_at|date:"Y/m/d H:i" }}
				</div>
			</div>
		</div>
		<div>
			<span class="base-font" style="font-size: large">{{ comment.content }}</span>
		</div>
		<br>
	</div>
{% endfor %}
</div>

community/templates/community/_like.html
<form class="d-inline like-form" data-article-id="{{ article.pk }}">
  {% csrf_token %}
  {% if user in article.like_users.all %}
    <button class="btn btn-link">
      <i id="like-{{ article.pk }}" class="like-btn fas fa-thumbs-up fa-2x"></i>
    </button>
  {% else %}
    <button class="btn btn-link">
      <i id="like-{{ article.pk }}" class="like-btn far fa-thumbs-up fa-2x"></i>
    </button>
  {% endif %}
</form>
<span id="like-count-{{ article.pk }}" class="base-font">
  {{ article.like_users.all|length }}명이 이 글을 추천합니다.
</span>

community/templates/community/create.html
{% extends 'base.html' %}

{% block title %}
  MoviePop | {{ movie.title }} 리뷰
{% endblock title %}

<head>
  {% load static %}
  {% block extrahead %}
  <link rel="stylesheet" href="{% static 'community/css/create.css' %}">
  {% endblock extrahead %}
</head>

{% block content %}

<div>
  <div class="col-row base-font d-flex justify-content-center">

    <div class="half col-5 m-0 p-0 d-flex justify-content-center">
      <div class="card mt-3" style="width: 20rem; background-color: rgba(17, 5, 2, 1);">
        <img src="https://image.tmdb.org/t/p/w500{{ movie.backdrop_path }}" class="card-img-top" alt="...">
        <div class="card-body p-0" style="background-color: rgba(17, 5, 2, 1); border-line: None;">
          <h5 class="card-title ml-2 mt-3">{{ movie.original_title }} | {{ movie.release_date.year }}</h5>
          <hr class="accounts-hr-color">
          <p class="card-text truncate ml-2" style="width: 250px; height: 190px; overflow: hidden;">{{ movie.overview }}</p>
          <a id="hover" href="{% url 'movies:detail' movie.movie_id %}" class="base-ivory btn m-0 p-0 ml-2 a-color-ivory">Movie Detail</a>
        </div>
      </div>
    </div>

    <div class="col-7 half mt-3 mr-5 p-0">
      <h4>영화 | {{ movie.title }}</h4>
      <hr class="accounts-hr-color">
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group" id="inputForm">
          <label for="formTitle"> 제목 </label>
          {{ form.title }}
          <br>
          <label for="formContent"> 본문 </label>
          {{ form.content }}
          <br>
          <div class="d-flex justify-content-between">
            {{ form.score }}
            {{ form.image }}
          </div>
          <input class="btn base-ivory" type="submit" id="hover">
          <a class="btn base-brightcrimson" href="{% url 'community:index' %}">back</a>
        </div>
      </form>
    </div>
  </div>
</div>
  <br>
  <br>

<!-- javascript -->
<script rel="stylesheet" src="{% static 'community/js/create.js' %}"></script>
{% endblock content %}

community/templates/community/detail.html
{% extends 'base.html' %}

<head>
  {% load static %}
  {% block extrahead %}
  <link rel="stylesheet" href="{% static 'community/css/detail.css' %}">
  {% endblock extrahead %}
</head>

{% block title %}
  MoviePop | {{ article.title }}
{% endblock title %}

{% block content %}
  <div class="d-flex content-align-right">
    <a class="btn back-btn btn-color-lightcrimson ml-auto page-font" href="{% url 'community:index' %}">
      뒤로가기
    </a>
  </div>
  {% comment %} <div style="background-color: rgba(255, 255, 255, 0.6); border-radius: 3rem;" class="container p-4"> {% endcomment %}
  <div class="container p-4">
    <h1 class="base-title-font pt-3 pl-3 base-ivory">{{ article.title }}</h1>
    <hr>
    <div class="p-3 text-brown-color">
      <div class="d-flex justify-content-between  align-items-center">
        <div>
          <span class="h4 base-title-font">작성자: 
            {% if article.user.image %}
              <img 
                class="m-0"
                src="{{ article.user.image.url }}" 
                alt="{{ article.user.image }}"
                width="30rem" 
                height="30rem" 
              >
            {% endif %}
            <a href="{% url 'accounts:detail' article.user.pk %}" class="atag">
              {{ article.user.nickname }}
            </a>
          </span>
        </div>
        <div>
          <div>
            <div class="base-font">최초 작성일 {{ article.created_at|date:"Y년 M d일 H:i" }}</div>
            <div class="base-font">최근 수정일 {{ article.updated_at|date:"Y년 M d일 H:i" }}</div>
          </div>
        </div>
      </div>
      <br>
      <div class="h5 text-brown-color base-title-font">후기 | {{ score }}</div>
    <br>

    <div class="d-flex justify-content-left">
      <div class="card mb-3" style="max-width: 540px; background-color: rgba(255, 255, 255, 0.2); border-radius: 1rem;">
        <div class="row no-gutters">
          <div class="col-md-4">
            <img 
              src="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" 
              class="card-img" 
              alt="..."
              style="height: 100%;"
            >
          </div>
          <div class="col-md-8">
            <div class="card-body" style="color: rgba(0, 0, 0, 1)">
              <a href="{% url 'movies:detail' movie.pk %}">
                <h5 class="card-title base-title-font" style="color: #ffffff;">{{ movie.title }}</h5>
              </a>
              <h5 class="mt-1 base-title-font" style="opacity: 0.4; color: #ffffff; font-size: 1rem;">{{ movie.original_title }} | {{ movie.release_date.year }}</h5>
              <hr>
              <div class="card-text base-font" style="color: #ffffff;">{{ movie.release_date }} | ⭐{{ movie.vote_average }}</div>
              <p class="card-text overview mt-2" style="color: #ffffff;">{{ movie.overview }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <hr>

      <div class="base-font base-ivory">
        {% comment %} <div class="h5 text-brown-color base-title-font">후기 | {{ score }}</div> {% endcomment %}
        <br>
        {% if article.image %}
          <div class="d-flex justify-content-center">
            <img 
              class="d-flex justify-content-center"
              src="{{ article.image.url }}" 
              alt="{{ article.image }}"
              width="700rem" 
            >
          </div>
        {% endif %}
        <br>
        <p class="text-brown-color base-font h5" style="line-height: 2rem;">{{ article.content }}</p>
      </div>
      <div class="d-flex justify-content-end align-items-center">
        {% if request.user == article.user %}
        <!-- 수정 -->
          <a href="{% url 'community:update' article.pk %}" class="m-1 icon-to-button-update">
  					<i class="fas fa-edit fa-2x"></i>
          </a>
        <!-- 삭제 -->
          <form action="{% url 'community:delete' article.pk %}" method="POST" class="m-1">
            {% csrf_token %}
  					{% comment %} <i class="far fa-trash-alt fa-2x"></i> {% endcomment %}
            <input type="submit" value="&#xf2ed;" class="btn search icon-to-button-delete p-0" style="font-size: 2rem;">
          </form>
        {% endif %}
      </div>
    </div>

    <div class="text-brown-color">
      {% include 'community/_like.html' %}
      <br>
      <br>
      <hr>
      <h4 class="base-title-font base-ivory">
        댓글
        {% if comments|length %}
          <span id="comment-count-{{ article.pk }}">
            ({{ article.comment_set.all|length }})
          </span>
        {% else %}
          <span id="comment-count-{{ article.pk }}">
            (0)
          </span>
        {% endif %}
      </h4>
      {% include 'community/_comment.html' %}
    </div>
    <div class="p-3 text-brown-color">
      {% include 'community/_commentlist.html' %}
    </div>
  </div>
  <br>

<!-- javascript -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script rel="stylesheet" src="{% static 'community/js/detail.js' %}"></script>
{% endblock content %}

community/templates/community/update.html
{% extends 'base.html' %}

{% block title %}
  MoviePop | 리뷰 수정
{% endblock title %}

<head>
  {% load static %}
  {% block extrahead %}
  <link rel="stylesheet" href="{% static 'community/css/update.css' %}">
  {% endblock extrahead %}
</head>

{% block content %}

<div>
  <div class="col-row base-font d-flex justify-content-center">

    <div class="half col-5 m-0 p-0 d-flex justify-content-center">
      <div class="card mt-3" style="width: 20rem; background-color: rgba(17, 5, 2, 1);">
        <img src="https://image.tmdb.org/t/p/w500{{ article.movie.backdrop_path }}" class="card-img-top" alt="...">
        <div class="card-body p-0" style="background-color: rgba(17, 5, 2, 1); border-line: None;">
          <h5 class="card-title ml-2 mt-3">{{ article.movie.original_title }} | {{ article.movie.release_date.year }}</h5>
          <hr class="accounts-hr-color">
          <p class="card-text truncate ml-2" style="width: 250px; height: 190px; overflow: hidden;">{{ article.movie.overview }}</p>
          <a id="a-hover" href="{% url 'movies:detail' article.movie.movie_id %}" class="btn m-0 p-0 ml-2 base-ivory">Movie Detail</a>
        </div>
      </div>
    </div>

    <div class="col-7 half mt-3 mr-5 p-0">
      <h4>영화 | {{ article.movie.title }}</h4>
      <hr class="accounts-hr-color">
      <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group" id="updateInputForm">
          <label for="formTitle"> 제목 </label>
          {{ form.title }}
          <br>
          <label for="formContent"> 본문 </label>
          {{ form.content }}
          <br>
          {{ form.score }}
          <input id="b-hover" class="btn base-ivory" type="submit">
          <a class="btn base-brightcrimson" href="{% url 'community:index' %}">[back]</a>
        </div>
      </form>
    </div>
  </div>
</div>
<br>
<br>

<!-- javascript -->
<script rel="stylesheet" src="{% static 'community/js/update.js' %}"></script>
{% endblock content %}