accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
    path('detail/<int:user_pk>', views.detail, name='detail'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/<int:movie_id>/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comments_update, name='comments_update'),
    path('<int:article_pk>/like/', views.like, name='like'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name="index"),
    path('preference/', views.preference, name='preference'),
    path('released_thisyear/', views.released_thisyear, name="released_thisyear"),
    path('alone/', views.alone, name="alone"),
    path('couple/', views.couple, name="couple"),
    path('together/', views.together, name="together"),
    path('<title>/<int:date>/', views.naver_link, name='naver_link'),
    path('<int:movie_id>/', views.detail, name='detail'),
    path('search/', views.search, name='search'),
    path('search_title/<str:searchword>', views.search_title, name='search_title'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from multiselectfield import MultiSelectField

from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    # preference = models.CharField(max_length=20)
    GENRES = (
        (12, '모험'),
        (14, '판타지'),
        (16, '애니메이션'),
        (18, '드라마'),
        (27, '공포'),
        (28, '액션'),
        (35, '코미디'),
        (36, '역사'),
        (37, '서부'),
        (53, '스릴러'),
        (80, '범죄'),
        (99, '다큐멘터리'),
        (878, 'SF'),
        (9648, '미스터리'),
        (10402, '음악'),
        (10749, '로맨스'),
        (10751, '가족'),
        (10752, '전쟁'),
        (10770, 'TV영화')
    )
    preference = MultiSelectField(choices = GENRES, verbose_name="선호하는 영화 장르")
    preference_code = models.CharField(max_length=20)
    nickname = models.CharField(max_length=10, verbose_name="닉네임")
    image = ProcessedImageField(
                null = True,
                blank = True,
                upload_to = 'profile/images/',
                processors = [ResizeToFill(300, 300)],
                format = 'JPEG',
                options = {'quality': 90},
                )

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from allauth.socialaccount.forms import SignupForm
from multiselectfield import MultiSelectField
from django.db import models

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('nickname', 'preference', 'image', )

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('nickname', 'preference', 'image', )

accounts/views.py
from .models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
)
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods, require_safe
from django.contrib.auth import update_session_auth_hash
from .forms import CustomUserChangeForm, CustomUserCreationForm


# 인덱스별 장르 id
# 인덱스에 따른 배치순서는 좋아하는 장르 통계 참고
match = [28, 18, 53, 10749, 10751,
            878, 14, 12, 35, 80,
            9648, 16, 99, 36, 10752, 
            27, 10402, 37, 10770
        ]


# 선호도 코드는 스트링형태로 저장
# 코드변환시에 int형태로 변환 후 수정
def make_pref_code(lis):
    idx_list = []
    for li in lis:
        idx_list.append(match.index(int(li)))
    code = '3333333333333333333'
    for idx in idx_list:
        code = code[:idx] + '5' + code[idx+1:]
    return code


@require_http_methods((['GET', 'POST']))
def signup(request):
    if request.user.is_authenticated:
        return redirect('community:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            print('~~~~~~~~~~~~~~~~')
            print(form)
            print('##################')
            print(user.image)
            # 1. user.preference => 리스트 자료형
            pre_list = user.preference
            # 2. 리스트 자료형 => 선호도 문자열 코드로 변환
            pre_code = make_pref_code(pre_list)
            # 3. 사용자 정보에 저장
            user.preference_code = pre_code
            user.save()
            auth_login(request, user)
            return redirect('community:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('community:index')
    
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'community:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    auth_logout(request)
    return redirect('community:index')


def update_code(pre, new, code):
    pre_idx = []
    new_idx = []
    # 리스트 형태로 전달된 이전, 이후 선호도의 idx를 추출
    for li in pre:
        pre_idx.append(match.index(int(li)))
    for li in new:
        new_idx.append(match.index(int(li)))
    # 추출된 인덱스 부분을 수정한다.
    for idx in pre_idx:
        # 에러 방지(2보다 작을 때 2를 빼면 필드범위를 벗어남 [1~9])
        if int(code[idx]) > 2:
            code = code[:idx] + str(int(code[idx]) - 2) + code[idx+1:]
    # 새로운 선호도 반영
    for idx in new_idx:
        if int(code[idx]) < 8:
            code = code[:idx] + str(int(code[idx]) + 2) + code[idx+1:]
    return code


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        # 1. 유저의 이전 선호도를 변수에 저장
        pre_pref = request.user.preference
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        print('################################')
        if form.is_valid():
            # 2. form에 새로 기입된 선호도가 user정보에 반영
            user = form.save()
            print('------------------------')
            print(user.image)
            # 3. user.preference는 새로반영된 선호도
            new_pref = user.preference
            pre_code = user.preference_code
            # 4. 이전 선호도 초기화 => 새로운 선호도 반영
            new_code = update_code(pre_pref, new_pref, pre_code)
            user.preference_code = new_code
            user.save()    

            return redirect('community:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
    return redirect('community:index')


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('community:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


@login_required
@require_http_methods(['GET'])
def detail(request, user_pk):
    # 1. user id, nickname
    # 2. 작성한 글, 댓글, 추천
    article_user = User.objects.get(pk=user_pk)
    request_user = request.user
    # 사용자, 글쓴이 정보 구별
    if article_user == request_user:
        user = request_user
    else:
        user = article_user
        
    articles = user.article_set.all()
    comments = user.comment_set.all()
    like_articles = user.like_articles.all()
    genre_code = user.preference_code
    context = {
        'user': user,
        'articles': articles,
        'comments': comments,
        'like_articles': like_articles,
        'genre_code': genre_code,
        'article_user': article_user,
    }
    return render(request, 'accounts/detail.html', context)

accounts/templates/accounts/_login_error.html
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog d-flex justify-content-center" role="document">
    <div class="modal-content" style="background-color: rgba(17, 5, 2, 0.8); width: 52rem;">
      <div class="modal-header">
        <h5 class="text-center modal-title base-title-font" id="exampleModalLabel" style="color: white;">경고</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: #ffffff;">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body d-flex justify-content-center align-items-center">
        <p>로그인에 실패했습니다..</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-color-lightcrimson base-title-font" data-dismiss="modal">Close</button>
        </a>
      </div>
    </div>
  </div>
</div>

accounts/templates/accounts/_preference_movie_genre.html
<h4 class="font-weight-bold">선호하는 영화 장르</h4>
<p style="color: white;">모두 선택해주세요 (최소 1개, 최대 19개 가능)</p>
<ul id="id_preference" class="mb-0" style="color: red"></ul>

<script>
  const addGenres = document.querySelector('#id_preference')
  const genres = [
    ['모험', 12], ['판타지', 14], ['애니메이션', 16], ['드라마', 18], 
    ['공포', 27], ['액션', 28], ['코미디', 35], ['역사', 36],
    ['서부', 37], ['스릴러', 53], ['범죄', 80], ['다큐멘터리', 99], 
    ['SF', 878], ['미스터리', 9648], ['음악', 10402], ['로맨스', 10749], 
    ['가족', 10751], ['전쟁', 10752], ['TV영화', 10770]
  ]

  let addGenreList = ""
  genres.forEach((genre, index) => {
    const addGenre = `
        <span>
          <label for="id_preference_${index}">
            <input class="input-checkbox" type="checkbox" name="preference" value="${genre[1]}" id="id_preference_${index}">
            ${genre[0]}
          </label>
        </span>
      `
    addGenreList += addGenre
  })

  addGenres.innerHTML = addGenreList
</script>

accounts/templates/accounts/_signup_form.html
<form action="" method="POST" class="accounts-form-width" enctype="multipart/form-data">
  {% csrf_token %}

  <hr class="accounts-hr-color">
  <h4 class="font-weight-bold mr-5 inline-block">아이디</h4>
  <input
    class="input-size"
    type="text" 
    name="username" 
    maxlength="150" 
    autocapitalize="none" 
    autocomplete="username" 
    autofocus="" 
    required="" 
    id="id_username" 
    placeholder="150자 이하 문자 및 숫자"
  >
  <hr class="accounts-hr-color">
  <h4 class="font-weight-bold mr-5 inline-block">닉네임</h4>
  <input 
    class="input-size"
    type="text" 
    name="nickname" 
    maxlength="10" 
    required="" 
    id="id_nickname" 
    placeholder="10자 이하"
  >
  <hr class="accounts-hr-color">
  <h4 class="font-weight-bold inline-block mr-4" style="font-size: 24.5px;">비밀번호</h4>
  <input 
    class="input-size"
    type="password" 
    name="password1" 
    autocomplete="new-password" 
    required="" 
    id="id_password1" 
    placeholder="최소 8자 이상"
  >
  <br>
  <br>
  <h6 
    class="font-weight-bold inline-block mr-3"
    style="font-size: 17.3px;"
  >
    비밀번호 확인
  </h6>
  <input 
    class="input-size"
    type="password" 
    name="password2" 
    autocomplete="new-password" 
    required="" 
    id="id_password2" 
    placeholder="최소 8자 이상"
  >
  <hr class="accounts-hr-color">
  <h4 class="font-weight-bold mr-5 inline-block">
    프로필
  </h4>
  <span style="color: white">
    {{ form.image }}
  </span>
  <br>
  <br>
  <hr class="accounts-hr-color">

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<h1>비밀번호 변경</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock content %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block title %}
  MoviePop | {{ user.nickname }}
{% endblock title %}

<head>
  {% block extrahead %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/css/detail.css' %}">
  {% endblock extrahead %}
</head>

{% block content %}

  <div>
    <div 
      class="base-font accounts-form-width userdetail base-ivory"
    >
      <hr class="accounts-hr-color">
      {% if user.image %}
        <img 
          class="d-flex justify-content-center"
          src="{{ user.image.url }}" 
          alt="{{ user.image }}"
          {% comment %} width="700rem"  {% endcomment %}
        >
      {% endif %}
      <h4 class="ml-3">🌽{{ user.nickname }}님의 Corn Graph🌽</h4>
      <br>
      <p id="genreData" style="display: None;">{{ genre_code }}</p>
      <canvas class="base-ivory" id="barChart"></canvas>
      <hr class="accounts-hr-color">
      <div class="">
        <h4 class="idnickname mr-4 ml-3" style="width: 100px;"> 아이디 |</h4>
        <h4 class="idnickname" style="width: 200px; color: white;">{{ user.username }}</h4>
        <hr class="accounts-hr-color">
        <h4 class="idnickname mr-4 ml-3" style="width: 100px;">닉네임 |</h4>
        <h4 class="idnickname" style="width: 200px; color: white;">{{ user.nickname }}</h4>
        <hr class="accounts-hr-color">
        <h4 class="ml-3">{{ user.nickname }}님의 리뷰 ({{ articles|length }})</h4>
        <div class="ml-5">
          {% for article in articles %}
            <a 
              class="atag" 
              href="{% url 'community:detail' article.pk %}"
            >
              <span style="font-weight: bold;">{{ article.movie }}</span> | {{ article.title|truncatechars:20 }} | {{ article.updated_at|date:"Y/m/d H:i" }}
            </a>
            <br>
          {% endfor %}
        </div>
        <hr>
        <h4 class="ml-3">{{ user.nickname }}님이 댓글단 리뷰 ({{ comments|length }})</h4>
        <div class="ml-5"> 
          {% for comment in comments %}
            <a 
              class="atag"
              href="{% url 'community:detail' comment.article.pk %}"
            >
              <span style="font-weight: bold;">{{ comment.content|truncatechars:20 }}</span> | {{ comment.article.title|truncatechars:20 }} | {{ comment.updated_at|date:"Y/m/d H:i" }}
            </a>
            <br>
          {% endfor %}
        </div>
        <hr>
        <h4 class="ml-3">{{ user.nickname }}님이 추천하는 리뷰 ({{ like_articles|length }})</h4>
        <div class="ml-5">
          {% for like in like_articles %}
            <a 
              class="atag" 
              href="{% url 'community:detail' like.pk %}"
            >
              <span style="font-weight: bold;">{{ like.movie }}</span> | {{ like.title|truncatechars:20 }}
            </a>
            <br>
          {% endfor %}
        </div>
        <hr>
        <br>
      </div>
    </div>
  </div>

  <script rel="stylesheet" src="{% static 'accounts/js/detail.js' %}"></script>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
  MoviePop | 로그인
{% endblock title %}

<head>
  {% block extrahead %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">
  {% endblock extrahead %}
</head>

{% block content %}
{% load socialaccount %}
{% providers_media_js %}

<br>
<br>

<hr>
<div class="d-flex justify-content-center">
  <form id="loginform" action="" method="POST" class="base-font">
  {% comment %} 로그인에 실패하는 경우
                (없는 계정이거나 비밀번호를 틀렸을 경우)
                따로 공지가 없다. -> 수정하기
  {% endcomment %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
                <div class="alert alert-danger">
                    <strong>{{ field.label }}</strong>
                    {{ error }}
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ error }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <div class="text-center">
      {% csrf_token %}
      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <span class="headcon input-group-text" id="basic-addon1">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
            </svg>
          </span>
        </div>
        {{ form.username }}
      </div>
      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <span class="headcon input-group-text" id="basic-addon2">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-key-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
            </svg>
          </span>
        </div>
        {{ form.password }}
      </div>
      <input
        style="width: 400px;"
        class="btn btn-warning mt-3" 
        type="submit" 
        value="로그인"
        data-target="#loginModal"
      >
      <br>
      <br>
      <span>
        <span style="color: white;">아직 MoviePop 회원이 아니세요? </span>
        <a href="{% url 'accounts:signup' %}">회원가입하기</a>
        <hr>
        <a href="{% provider_login_url 'google' %}">구글 로그인</a>
        <a href="{% provider_login_url 'naver' %}">네이버 로그인</a>
      </span>
    </div>
  </form>
</div>

<script rel="stylesheet" src="{% static 'accounts/js/login.js' %}"></script>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}
  MoviePop | 회원가입
{% endblock title %}

<head>
  {% block extrahead %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/css/signup.css' %}">
  {% endblock extrahead %}
</head>

{% block content %}
  <br>
  <br>
  <div class="base-brightcrimson base-font">
    <div class="d-flex justify-content-center">
        {% include 'accounts/_signup_form.html' %}
        {% include 'accounts/_preference_movie_genre.html' %}
        <div class="flex-center-vertically">
          <input class="btn btn-color-ivory btn-width" type="submit" value="회원가입">
          <button class="btn btn-secondary btn-width">취소</button>
          <br>
        </div>
        <br>
        <span>이미 MoviePop 계정이 있다면 ? </span>
        <a href="{% url 'accounts:login' %}">로그인하기</a>
      </form>
    </div>
    <br>
  </div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block title %}
  MoviePop | 정보수정
{% endblock title %}

<head>
  {% block extrahead %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/css/update.css' %}">
  {% endblock extrahead %}
</head>

{% block content %}

<br>

<div class="accounts-form-width userdetail base-font base-ivory">
  <hr class="accounts-hr-color">
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h4 class="idnickname mr-4" style="width: 100px;"> My ID  </h4>
    <h4 class="idnickname" style="width: 200px; color: white;">{{ user.username }}</h4>
    <hr class="accounts-hr-color">
    <h4 class="idnickname mr-4" style="width: 100px;">Name</h4>
    {{ form.nickname }}
    <hr class="accounts-hr-color">
    <h4 class="idnickname mr-4" style="width: 100px;">비밀번호</h4>
    <a href="../password/" class="h5 font-weight-bold atag">비밀번호 변경하기</a>
    <hr class="accounts-hr-color">
    <h4 class="idnickname mr-4" style="width: 100px;"> 프로필  </h4>
    <span style="color: white">
      {{ form.image }}
    </span>
    <hr class="accounts-hr-color">

    <h5 class="font-weight-bold">선호하는 영화 장르</h5>
    <br>
    <div id="preference">
      {{ form.preference }}
    </div>

    <div class="d-flex justify-content-center">
    <input class="btn btn-color-ivory btn-width base-title-font" type="submit" value="수정완료">
    <a class="btn btn-secondary btn-width base-title-font" href="{% url 'community:index' %}">취소</a>
    </div>
  </form>
  <br>
  <form action="{% url 'accounts:delete' %}" method="POST" class="idnickname">
    {% csrf_token %}
    <input class="button atag" type="submit" value="회원탈퇴하기">
  </form>
  <br>
  <br>
</div>

<script rel="stylesheet" src="{% static 'accounts/js/update.js' %}"></script>

{% endblock content %}